import './sass/main.scss';
import API from './scripts/services/API';
import renderMainPage from './scripts/renderMainPage';
import { scrollToTop } from './scripts/scroll-to-top';
import header from './scripts/header';
import pagination from './scripts/pagination';
import spinner from './scripts/spinner';
import './scripts/searchMovie';
import modalStudents from './scripts/modalStudents';
import darkTheme from './scripts/dark-theme';
import sortingBtns from './scripts/sortingBtns';
import './scripts/infiniteScroll';
